# Generated by Django 5.2 on 2025-06-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retinoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paciente",
            options={"verbose_name": "Paciente", "verbose_name_plural": "Pacientes"},
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="email",
        ),
        migrations.AddField(
            model_name="paciente",
            name="alergias",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="enfermedades_cronicas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="pacientes/"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="grupo_sanguineo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
