# Generated by Django 5.2.1 on 2025-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retinoapp', '0002_alter_paciente_options_remove_paciente_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenretina',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='imagenretina',
            name='confianza',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imagenretina',
            name='nombre_escaneo',
            field=models.CharField(default='Escaneo', max_length=200),
        ),
        migrations.AlterField(
            model_name='imagenretina',
            name='resultado',
            field=models.CharField(choices=[('0', 'Sin Retinopatía'), ('1', 'RD Leve'), ('2', 'RD Moderada'), ('3', 'RD Severa'), ('4', 'RD Proliferativa')], max_length=2),
        ),
    ]
